blog/urls.py
from django.urls import path
from .views import PostDeleteView, PostDetailView, PostListView, PostCreateView, PostUpdateView, UserPostListView

app_name = 'blog'

urlpatterns = [
    path('article/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'), 
    path('article/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('article/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('article/create/', PostCreateView.as_view(), name='post-create'),
    path('posts/<username>', UserPostListView.as_view(), name='user-posts'),
    path('', PostListView.as_view(), name='blog-home'),
]

csrf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as users_views
from .views import UserLoginView, UserLogoutView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', users_views.register, name='register'),
    path('profile/', users_views.profile, name='profile'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse


class Post(models.Model):
    title       = models.CharField(max_length=100)
    content     = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author      = models.ForeignKey(User, on_delete=models.CASCADE)
    image       = models.ImageField(default='default.jpg', upload_to='post_images')

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("blog:post-detail", kwargs={"pk": self.pk})
    

users/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

    # this is from someone comment issue and dibantu corey
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class UserRegisterForm(UserCreationForm):
    email   = forms.EmailField()
    class Meta:
        model = User
        fields = [
            'username', 'email', 'password1', 'password2'
        ]

class UserUpdateForm(forms.ModelForm):
    email   = forms.EmailField()
    class Meta:
        model = User
        fields = [
            'username', 'email'
        ]

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = [
            'image'
        ]

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.views.generic.edit import DeleteView
from django.contrib.auth.models import User
from .models import Post

# Using CBV
class PostListView(ListView):
    
    model = Post
    template_name = 'blog/home.html'
    context_object_name = 'posts' #ini sama aja posts = Post.objects.all() dan return Queryset, kalau gk di kasih ini defaultnya bukan 'posts' tapi 'objects'/'object' (lupa)
    ordering = ['-date_posted']
    paginate_by = 6



class UserPostListView(ListView):
    
    model = Post
    template_name = 'blog/user_posts.html'
    context_object_name = 'posts'
    paginate_by = 4
    
    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')



class PostDetailView(DetailView):
    
    model = Post
    template_name = 'blog/article.html'
    context_object_name = 'post'



class PostCreateView(LoginRequiredMixin, CreateView):
    
    model = Post
    fields = ['title', 'content', 'image']
    template_name = 'blog/create.html'
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
        


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    
    model = Post
    fields = ['title', 'content', 'image']
    template_name = 'blog/create.html'
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
    def test_func(self):
        post = self.get_object()
        return True if self.request.user == post.author else False
    
 
    
class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    
    model = Post
    template_name = 'blog/delete.html'
    ontext_object_name = 'post'
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        return True if self.request.user == post.author else False



def about(request):
    context = {
        'title': 'About Page'
    }
    return render(request, 'blog/about.html', context)

csrf/views.py
from django.contrib.auth.views import LogoutView, LoginView
from django.contrib import messages
from django.shortcuts import redirect
from django.utils.decorators import method_decorator

class UserLoginView(LoginView):
    template_name = 'users/login.html'
    redirect_authenticated_user = True


class UserLogoutView(LogoutView):
    # template_name = 'users/logout.html'

    # print('iam here')
    # def get(self, request, *args, **kwargs):
    #     print(self.request)
    #     print('oioi')

    def get_next_page(self):
        # print(self.request.session.values())
        # if self.request.user.is_authenticated:
        next_page = super(UserLogoutView, self).get_next_page()
        # messages.success(self.request, f'Kamu telah berhasil logout !')
        return next_page #ini mengeksekusi variable `next_page` di parent class yg mana mengarah ke setting.LOGOUT_REDIRECT_URL
        # else:
        #     next_page = super(UserLogoutView, self).get_next_page()
        #     messages.warning(self.request, 'Hah ???')
        #     return next_page

users/views.py
from django.shortcuts import render, redirect
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
    # else:
    #     form = UserRegisterForm()
def register(request):
    if request.user.is_authenticated:
        return redirect('blog:blog-home')
    else:
        form = UserRegisterForm()
    
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, f'Acccount successfully created !')
            return redirect('login')


    context = {
        'form': form
    }
    return render(request, 'users/register.html', context)


@login_required
def profile(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        prof_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if user_form.is_valid() and prof_form.is_valid():
            user_form.save()
            prof_form.save()
            messages.success(request, f'Account has been updated !')
            return redirect('profile')
        
    user_form = UserUpdateForm(instance=request.user)
    prof_form = ProfileUpdateForm(instance=request.user.profile)
    
    context = {
        'user_form': user_form,
        'prof_form': prof_form
    }
    return render(request, 'users/profile.html', context)

blog/templates/blog/article.html
<!-- django default render is post_create.html 
	PostDetailView uses this
-->
{% extends 'blog/base.html' %}
{% block content %}
    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{% url 'blog:user-posts' post.author.username %}">{{ post.author }}</a>
                <small class="text-muted">{{ post.date_posted|date:"d F Y" }}</small>
            </div>
            <h2 class="article-title">{{ post.title }}</h2>
            {% if object.image.url != "/media/default.jpg" %}
                <img style="width:50%; height:auto;" class="img-responsive" src="{{ post.image.url }}">
            {% endif %}
            <p class="article-content">{{ post.content }}</p>
        </div>
        {% if post.author == user %}
        <div>
            <a class="btn btn-danger btn-sm" href="{% url 'blog:post-delete' post.id %}">Delete</a>
            <a class="btn btn-secondary btn-sm" href="{% url 'blog:post-update' post.id %}">Update</a>
        </div>
        {% endif %}
    </article>
{% endblock content %}

{% block samping %}
<div class="content-section">
    <h3 class="pt-2 pb-2">Side Navigation</h3>

    <ul class="list-group">
        {% if user.is_authenticated %}
            <div>
                <a class="nav-item nav-link bg-primary p-2 text-white text-center mb-3"
                    href="{% url 'profile' %}">Profile</a>
            </div>
            <div>
                <a class="nav-item nav-link bg-primary p-2 text-white text-center mb-3"
                    href="{% url 'blog:post-create' %}">Create Post</a>
            </div>
            <div>
                <a class="nav-item nav-link bg-danger p-2 text-white text-center mb-3" href="{% url 'logout' %}">Logout</a>
            </div>
        {% else %}
            <div>
                <a class="nav-item nav-link bg-info p-2 text-white text-center mb-3"
                    href="{% url 'register' %}">Register</a>
            </div>
            <div>
                <a class="nav-item nav-link bg-primary p-2 text-white text-center mb-3" href="{% url 'login' %}">Login</a>
            </div>
        {% endif %}
    </ul>
</div>
{% endblock samping %}

blog/templates/blog/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'blog/main.css' %}">
    {% if title %}w
        <title>Simple - {{ title }}</title>
    {% else %}
        <title>Simple Blog</title>
    {% endif %}

  </head>
  <body>
    <header class="site-header">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container">
            <a class="navbar-brand mr-4" href="{% url 'blog:blog-home' %}">Simple Blog</a>
            
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item mx-2">
                        <a class="nav-link active" href="{% url 'blog:blog-home' %}">Home</a>
                    </li>
                    {% if not user.is_authenticated %}
                        {% comment %} <li class="nav-item mx-2">
                            <a class="nav-item nav-link" href="{% url 'blog:post-create' %}">Create Post</a>
                        </li>
                        <li class="nav-item mx-2">
                            <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                        </li>
                        <li class="nav-item mx-2">
                            <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                        </li>
                    {% else %} {% endcomment %}
                        <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                        <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                    {% endif %}
                </ul>
            </div>
                <!-- Navbar Right Side -->
                {% comment %} <div class="navbar-nav">
                {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'blog:post-create' %}">Create Post</a>
                    <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                    <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                {% else %}
                    <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                    <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                {% endif %}
                </div> {% endcomment %}
            </div>
        </nav>
        </header>
        <main role="main" class="container">
            <div class="row">
                <div class="col-md-8">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }}">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% block content %}{% endblock content %}
                </div>
                <div class="col-md-4">
                    {% block samping %}{% endblock samping %}
                </div>
            </div>
        </main>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script> -->
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

blog/templates/blog/create.html
<!-- django default render is post_create.html 
	UpdateView and Create View use this
-->
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST" enctype='multipart/form-data'>
            {% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Blog Post</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group mt-4 mb-2">
				<button type="submit" class="btn btn-outline-info">Create Post</button>
			</div>
        </form>
    </div>
{% endblock content %}

{% block samping %}
<div class="content-section">
    <h3 class="pt-2 pb-2">Side Navigation</h3>

    <ul class="list-group">
        {% if user.is_authenticated %}
            <div>
                <a class="nav-item nav-link bg-info p-2 text-white text-center mb-3"
                    href="{% url 'profile' %}">Profile</a>
            </div>
            <div>
                <a class="nav-item nav-link bg-danger p-2 text-white text-center mb-3" href="{% url 'logout' %}">Logout</a>
            </div>
        {% endif %}
    </ul>
</div>
{% endblock samping %}

blog/templates/blog/delete.html
{% extends 'blog/base.html' %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Blog Post</legend>
                <h2>Apakah anda yakin ingin menghapus post "{{ post.title }}" ?</h2>
			</fieldset>
			<div class="form-group">
				<button type="submit" class="btn btn-outline-danger">Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'blog:post-detail' post.id %}">Cancel</a>
			</div>
        </form>
    </div>
{% endblock content %}

blog/templates/blog/home.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in posts %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
            <div class="media-body">
                <div class="article-metadata">
                <a class="mr-2" href="{% url 'blog:user-posts' post.author.username %}">{{ post.author }}</a>
                <small class="text-muted">{{ post.date_posted|date:"d F Y" }}</small>
                </div>
                <h2><a class="article-title" href="{% url 'blog:post-detail' post.id %}">{{ post.title }}</a></h2>
                {% if post.content|length > 150 %}
                    <p class="article-content">{{ post.content|truncatewords:50 }} <a href="{% url 'blog:post-detail' post.id %}">more...</a></p>
                {% else %} 
                    <p class="article-content">{{ post.content }}</p>
                {% endif %}
            </div>
        </article>
    {% endfor %}

    <!-- PAGINATOR -->
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Prev</a>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-2' and num < page_obj.number|add:'2' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}
    {% endif %}
{% endblock content %}

{% block samping %}
<div class="content-section">
    <h3 class="pt-2 pb-2">Side Navigation</h3>

    <ul class="list-group">
        {% if user.is_authenticated %}
            <div>
                <a class="nav-item nav-link bg-info p-2 text-white text-center mb-3"
                    href="{% url 'profile' %}">Profile</a>
            </div>
            <div>
                <a class="nav-item nav-link bg-primary p-2 text-white text-center mb-3"
                    href="{% url 'blog:post-create' %}">Create Post</a>
            </div>
            <div>
                <a class="nav-item nav-link bg-danger p-2 text-white text-center mb-3" href="{% url 'logout' %}">Logout</a>
            </div>
        {% else %}
            <div>
                <a class="nav-item nav-link bg-info p-2 text-white text-center mb-3"
                    href="{% url 'register' %}">Register</a>
            </div>
            <div>
                <a class="nav-item nav-link bg-primary p-2 text-white text-center mb-3" href="{% url 'login' %}">Login</a>
            </div>
        {% endif %}
    </ul>
</div>
{% endblock samping %}

blog/templates/blog/test.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
      <div class="container">
        <a class="navbar-brand" href="#">Simple Blog</a>
        <a class="nav-link active" href="#">Homes</a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <li class="nav-item mx-2">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item mx-2">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

  

    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

blog/templates/blog/user_posts.html
{% extends 'blog/base.html' %}
{% block content %}
    <div class="ctg">
        <h4>Posts by {{ view.kwargs.username }}, Total : {{ page_obj.paginator.count }} Post(s)</h4>
    </div>
    {% for post in posts %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
            <div class="media-body">
                <div class="article-metadata">
                <a class="mr-2" href="{% url 'blog:user-posts' post.author.username %}">{{ post.author }}</a>
                <small class="text-muted">{{ post.date_posted|date:"d F Y" }}</small>
                </div>
                <h2><a class="article-title" href="{% url 'blog:post-detail' post.id %}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}

    <!-- PAGINATOR -->
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Prev</a>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-2' and num < page_obj.number|add:'2' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}
    {% endif %}
{% endblock content %}

{% block samping %}
<div class="content-section">
    <h3 class="pt-2 pb-2">Side Navigation</h3>

    <ul class="list-group">
        {% if user.is_authenticated %}
            <div>
                <a class="nav-item nav-link bg-info p-2 text-white text-center mb-3"
                    href="{% url 'profile' %}">Profile</a>
            </div>
            <div>
                <a class="nav-item nav-link bg-primary p-2 text-white text-center mb-3"
                    href="{% url 'blog:post-create' %}">Create Post</a>
            </div>
            <div>
                <a class="nav-item nav-link bg-danger p-2 text-white text-center mb-3" href="{% url 'logout' %}">Logout</a>
            </div>
        {% else %}
            <div>
                <a class="nav-item nav-link bg-info p-2 text-white text-center mb-3"
                    href="{% url 'register' %}">Register</a>
            </div>
            <div>
                <a class="nav-item nav-link bg-primary p-2 text-white text-center mb-3" href="{% url 'login' %}">Login</a>
            </div>
        {% endif %}
    </ul>
</div>
{% endblock samping %}

users/templates/users/login.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Log In</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group mb-4">
				<button type="submit" class="btn btn-outline-info">Login</button>
			</div>
        </form>
		<div class="border-top pt-3">
			<small class="text-muted">
				Need an account ? <a href="{% url 'register' %}" class="ml-2">Sign Up Now</a>
			</small>
		</div>
    </div>
{% endblock content %}

users/templates/users/profile.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <div class="media">
            <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
            <div class="media-body">
                <h2 class="account-heading">{{ user.username }}</h2>
                <p class="text-secondary">{{ user.email }}</p>
            </div>
        </div>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profile Information</legend>
                {{ user_form|crispy }}
                {{ prof_form|crispy }}
            </fieldset>
            <div class="form-group">
                <button type="submit" class="btn btn-outline-info mt-4 mb-2">Update</button>
            </div>
        </form>
    </div>
{% endblock content %}

{% block samping %}
<div class="content-section">
    <h3 class="pt-2 pb-2">Side Navigation</h3>

    <ul class="list-group">
        {% if user.is_authenticated %}
            <div>
                <a class="nav-item nav-link bg-primary p-2 text-white text-center mb-3"
                    href="{% url 'blog:post-create' %}">Create Post</a>
            </div>
            <div>
                <a class="nav-item nav-link bg-danger p-2 text-white text-center mb-3" href="{% url 'logout' %}">Logout</a>
            </div>
        {% endif %}
    </ul>
</div>
{% endblock samping %}

users/templates/users/register.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Sign Up Now</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group mb-3 mt-2">
				<button type="submit" class="btn btn-outline-info">Register</button>
			</div>
        </form>
		<div class="border-top pt-3">
			<small class="text-muted">
				Already Have an Account ? <a href="{% url 'login' %}" class="ml-2">Sign In</a>
			</small>
		</div>
    </div>
{% endblock content %}